import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// In dev, build directly into the dev vault so Obsidian picks up changes.
// In prod (release builds), output to the repo root so the release artifacts
// can be uploaded to GitHub.
const devVaultPluginDir = join(
	'dev-vault',
	'.obsidian',
	'plugins',
	'jot',
);
const outdir = prod ? '.' : devVaultPluginDir;
const outfile = join(outdir, 'main.js');

if (!prod) {
	mkdirSync(devVaultPluginDir, { recursive: true });
}

const copyStaticAssets = () => {
	for (const file of ['manifest.json', 'styles.css']) {
		if (existsSync(file)) {
			copyFileSync(file, join(outdir, file));
		}
	}
};

const copyAssetsPlugin = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd(() => copyStaticAssets());
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: prod,
	plugins: [copyAssetsPlugin],
});

if (prod) {
	await context.rebuild();
	copyStaticAssets();
	process.exit(0);
} else {
	await context.watch();
	copyStaticAssets();
}
